### ISSUE TITLE
css

### ISSUE THREAD

**Issue by marte-git** [eXplosive57/Contributo-1-Kerrouche.XHTML_CSS#1]
penso che dovrebbe limitae al massimo il numero di file css

sicuramente li puo' accorpare e usare a volte le classi per distinguere il trattamento di un selettore in diversi file

sorry per averci messo un po'; questo mi era sfuggito

risponda qui cosi' poi dichiaro l'issue chiuso

**Comment by eXplosive57** [comment]
La ringrazio per la risposta. Ho eseguito l'update del file css.
